spring.application.name=employeedetails
logging.level.root=ERROR

spring.datasource.url=jdbc:postgresql://localhost:5432/Ems_DB
spring.datasource.username=<DB user>
spring.datasource.password=<DB password>
spring.jpa.hibernate.ddl-auto=update
